server:
  servlet:
    # 应用的访问路径
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true

# Spring配置
spring:
  application:
    name: wash-car-admin
  profiles:
    # 环境配置
    active: dev
  aop:
    proxyTargetClass: true
  jackson:
    default-property-inclusion: non_null
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  mvc:
    format:
      dateTime: yyyy-MM-dd HH:mm:ss

# Mybatis配置
mybatis:
  #搜索指定包别名
  type-aliases-package: com.wash.car
  #加载全局的配置文件
  config-location: classpath:mybatis/mybatis-config.xml
  #配置mapper的扫描，找到所有的mapper.xml映射文件
  mapper-locations: classpath*:mybatis/mapper/*/*.xml
  check-config-location: true

# 日志配置
logging:
  level:
    com.wash.car.mapper: DEBUG
    org.springframework: warn

washcar:
  jwt:
    # 加密秘钥
    secret: washcar
    # token有效时长，24小时，单位秒
    expire: 86400
    header: token
